# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7acc8fe93e433813f540fb7e907a342917581a8e00150d8851fa2ed6ae0a83d6610a16ac1733ab54b68feb5e18a5087a7b24b1a51dbdc220a3ed7800f131ecfd

test:
  secret_key_base: bd5fff13ddb33efd214e1983774b678326dbb10bcb3574d9acceb3c6a81042fc6465d6818bae5f1f899d50e94e49e7867374a8a185451b7eba2cba64459397fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
